auctionbot/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

brands/urls.py
from django.conf.urls import url

from . import views



app_name = "brands"

urlpatterns = [
    url(
        regex   = r'^$',
        view    = views.BrandIndexView.as_view(),
        name    = 'index' ),
    url(
        regex   = r'^add/$',
        view    = views.BrandCreateView.as_view(),
        name    = 'add'  ),
    url(
        regex   = r'^(?P<pk>[0-9]+)/$',
        view    = views.BrandDetailView.as_view(),
        name    = 'detail'),
    url(
        regex   = r'^delete/(?P<pk>[0-9]+)/$',
        view    = views.BrandDeleteView.as_view(),
        name    = 'delete'),
    url(
        regex   = r'^edit/(?P<pk>[0-9]+)/$',
        view    = views.BrandUpdateView.as_view(),
        name    = 'edit' ),

]

'''
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new$', views.CreateBrandView.as_view(),
        name='brands-new',),
'''

auctionbot/users/models.py
from django.db              import models
from django.urls            import reverse

from core.dj_import         import AbstractUser, _

import pytz
from timezone_field         import TimeZoneField

from ebayinfo.models        import Market

iEbayUSA = Market.objects.get(
            cMarket = 'EBAY-US' ).pk or 0 # on error may need to comment out!

# iEbayUSA = 0 # uncomment this one if the above is causing migration error

class User(AbstractUser):
    # First Name and Last Name do not cover name patterns
    # around the globe.
    name        = models.CharField(_('Name of User'), blank=True, max_length=255)
    #models.ForeignKey( Market, models.PositiveIntegerField(
    iEbaySiteID = models.ForeignKey( Market, on_delete=models.CASCADE,
                    verbose_name = 'ebay market (default)',
                    default = iEbayUSA )

    '''for testing, it is a big challenge to set default iEbaySiteID from markets table,
    because when testing, markets table starts out empty'''

    cBio        = models.TextField( 'Bio info', max_length=500, blank=True)
    cLocation   = models.CharField( 'Location', max_length=30, blank=True)
    zTimeZone   = TimeZoneField( default = 'UTC' )

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

brands/models.py
from django.db                  import models
from django_countries.fields    import CountryField
from django.core.exceptions     import FieldDoesNotExist
from django.utils               import timezone

# Create your models here.

from django.contrib.auth        import get_user_model

from core.models                import ( IntegerRangeField, sTitleHelpText,
                                         sLookForHelpText, sExcludeIfHelpText,
                                         sLookForHeading, sKeyWordsHelpText )

from core.mixins                import GetItemsForSomething

from core.utils                 import getReverseWithUpdatedQuery

User = get_user_model()

# ### models can be FAT but not too FAT! ###


_sExplainMore = (
        '%%s<br/>Bot expands spaces and hyphens,<br/>'
        '"Hewlett-Packard" will %s Hewlett-Packard, Hewlett Packard and HewlettPackard,<br/>'
        '"Hewlett Packard" will %s Hewlett Packard, Hewlett-Packard and HewlettPackard' )

_sExplainMoreFinding = _sExplainMore % ( 'find', 'find' )

_sExplainMoreExclude = _sExplainMore % ( 'exclude', 'exclude' )


_sHelpTextBrandTitle = (
        _sExplainMoreFinding %
        ( sTitleHelpText % ( 'brand', '' ) ) )

sExample = "For example, if the brand is Chevrolet, put 'Chevy' here<br>"

_sHelpTextBrandLookFor = (
        _sExplainMoreFinding %
        ( sLookForHelpText %
            ( 'brand', 'brand', sExample, 'brand' ) ) )

_sHelpTextBrandExcludeIf = (
        _sExplainMoreExclude %
        ( sExcludeIfHelpText % 'brand' ) )


class Brand( GetItemsForSomething, models.Model ):
    cTitle          = models.CharField(
                        'brand name', max_length = 48, db_index = True,
        help_text   = _sHelpTextBrandTitle )
    bWanted         = models.BooleanField(
                        'want anything from this brand?', default = True,
        help_text = 'Bot will only download full descriptions and pictures '
                    'if you want' )
    bAllOfInterest  = models.BooleanField(
                        'want everything from this brand?', default = True,
        help_text = 'Definitely set to True for desireable & rare brands' )
    cLookFor        = models.TextField( sLookForHeading,
                        null=True, blank = True,
        help_text   = _sHelpTextBrandLookFor )
    cKeyWords       = models.TextField(
                        'brand key words',
                        null = True, blank = True,
        help_text = sKeyWordsHelpText % (
                        '', 'brand', 'brand' ) )
    iStars          = IntegerRangeField(
                        'desireability, 10 star brand is most desireable',
                        min_value = 0, max_value = 10, default = 5 )
    cComment        = models.TextField( 'comments', null = True, blank = True)
    cNationality    = CountryField( "nationality",  null = True, blank = True,
                        blank_label='(select country)' )
    cExcludeIf      = models.TextField(
                        'Not a hit if this text is found (optional)',
                        null=True, blank = True,
        help_text   = _sHelpTextBrandExcludeIf )

    cRegExLook4Title= models.TextField( null = True )
    cRegExExclude   = models.TextField( null = True )
    cRegExKeyWords  = models.TextField( null = True )

    iLegacyKey      = models.PositiveIntegerField('legacy key', null = True )
    tLegacyCreate   = models.DateTimeField( 'legacy row created on',
                        null=True, blank = True )
    tLegacyModify   = models.DateTimeField( 'legacy row updated on',
                        null=True, blank = True )
    iUser           = models.ForeignKey( User, verbose_name = 'Owner',
                        on_delete=models.CASCADE )
    tCreate         = models.DateTimeField( 'created on', auto_now_add= True )
    tModify         = models.DateTimeField( 'updated on', auto_now    = True )
    #

    def __str__(self):
        return self.cTitle

    class Meta:
        verbose_name        = 'brand name'
        verbose_name_plural = 'brands'
        ordering            = ('cTitle',)
        db_table            = verbose_name_plural
        unique_together     = ('cTitle','iUser')

    def getCategoriesForBrand( self, oBrand ):
        #
        from categories.models  import Category
        from categories.models  import BrandCategory
        #
        oBrandCategories = BrandCategory.objects.filter( iBrand = oBrand )
        #
        oCategories = Category.objects.filter(
            id__in = BrandCategory.objects.values_list("iCategory").filter(
                iBrand = oBrand ) ).order_by( 'cTitle' )
        #
        return oCategories

    def getModelsForBrand( self, oBrand ):
        #
        from models.models import Model
        #
        oModels = Model.objects.filter( iBrand = oBrand ).order_by( 'cTitle' )
        #
        l = [ ( oModel, oModel.iStars, oModel.iCategory )
              for oModel in oModels ]
        #
        return l


    def getKeeperQsetForThis( self, oBrand, oUser ):
        #
        from keepers.models import UserKeeper
        #
        qsUserItems = (
            UserKeeper.objects.filter(
                iUser  = oUser,
                iBrand = oBrand ) )
        #
        return qsUserItems



    def getFinderQsetForThis( self, oBrand, oUser ):
        #
        from finders.models import UserItemFound
        #
        # ugh!
        # solution: denormalize, also keep tTimeEnd in UserItemFound
        #
        # qsUserItems = (
        #     UserItemFound.objects.filter(
        #         iUser  = oUser,
        #         iBrand = oBrand ).filter(
        #         iItemNumb__in = (
        #             ItemFound.objects.filter(
        #                 tTimeEnd__gt = timezone.now()
        #                 ).values_list( 'iItemNumb', flat=True ) ) ) )
        #
        qsUserItems = (
            UserItemFound.objects.filter(
                iUser               = oUser,
                iBrand              = oBrand,
                tRetrieved__isnull  = True )
            ).order_by( '-iHitStars', '-tTimeEnd' )
        #
        return qsUserItems


    def get_absolute_url(self):
        #
        return getReverseWithUpdatedQuery(
                'brands:detail',
                kwargs = { 'pk': self.pk, 'tModify': self.tModify } )

brands/forms.py
from core.forms         import ModelFormValidatesTitle
from django.forms       import ModelForm, formset_factory, BooleanField

from core.crispy        import Field, Layout, Submit
from .models            import Brand

from categories.models  import Category

# ### forms validate the incoming data against the database      ###
# ### additional custom validation logic can be implemented here ###
# ### crispy forms adds automatic layout functionality           ###

tModelFields = (
    'cTitle',
    'bWanted',
    'bAllOfInterest',
    'cLookFor',
    'cKeyWords',
    'iStars',
    'cComment',
    'cNationality',
    'cExcludeIf' )


def _getLayout():
    #
    return Layout(
            'cTitle',
            'bWanted',
            'bAllOfInterest',
            Field('cLookFor',  rows='2'),
            Field('cKeyWords', rows='2'),
            'iStars',
            Field('cComment',  rows='2'),
            'cNationality',
            Field('cExcludeIf',rows='2') )


class CreateBrandForm( ModelFormValidatesTitle ):
    #

    def __init__( self, *args, **kwargs ):
        #
        super().__init__( *args, **kwargs )
        #
        self.helper.form_tag = False
        #self.helper.add_input(Submit('submit', 'Create', css_class='btn-primary'))
        #self.helper.add_input(Submit('cancel', 'Cancel', css_class='btn-primary'))
        #
        self.helper.layout = _getLayout()

    class Meta:
        model  = Brand
        fields = tModelFields


class UpdateBrandForm( ModelFormValidatesTitle ):
    #

    def __init__( self, *args, **kwargs ):
        #
        super().__init__( *args, **kwargs )
        #
        self.helper.form_tag = False
        #self.helper.add_input(Submit('submit', 'Update', css_class='btn-primary'))
        #self.helper.add_input(Submit('cancel', 'Cancel', css_class='btn-primary'))
        #
        self.helper.layout = _getLayout()
        #


    class Meta:
        model  = Brand
        fields = tModelFields

auctionbot/users/views.py
from django.urls                import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User

tUserFields = (
    'name',
    'iEbaySiteID',
    'cBio',
    'cLocation',
    'email',
    'zTimeZone'
    )

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'



class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = tUserFields[:-1]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User

    fields = tUserFields

    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

brands/views.py
from django.http            import HttpResponseRedirect
from django.urls            import reverse_lazy

from core.mixins            import ( WereAnyReleventRegExColsChangedMixin,
                                     TitleSearchMixin )

from core.utils             import model_to_dict
from core.views             import (
                                CreateViewCanCancel, DeleteViewGotModel,
                                ListViewGotModel, UpdateViewCanCancel,
                                DetailViewGotModelAlsoPost )

from .forms             import CreateBrandForm, UpdateBrandForm
from .mixins            import ( GetContextForBrandCategoryList,
                                 PostUpdateBrandCategoryList )
from .models            import Brand

from categories.models  import Category, BrandCategory
from models.models      import Model
from keepers.utils      import deleteKeeperUserItem


# ### views assemble presentation info ###
# ###         keep views thin!         ###


class BrandCreateView( GetContextForBrandCategoryList,
                       PostUpdateBrandCategoryList, CreateViewCanCancel ):

    model           = Brand
    template_name   = 'brands/add.html'
    form_class      = CreateBrandForm

    success_message = 'New Brand record successfully saved!!!!'






class BrandDeleteView( DeleteViewGotModel ):

    model           = Brand
    template_name   = 'brands/confirm_delete.html'
    success_message = 'Brand record successfully deleted!!!!'
    success_url     = reverse_lazy('brands:index')




class BrandDetailView( DetailViewGotModelAlsoPost ):

    model   = Brand
    template_name = 'brands/detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the categories
        #context['fields_list'] = Brand.getFieldsForView(
        #
        #context['model_fields' ] = tModelFields
        #context['dFieldsValues'] = model_to_dict( context['model'] )
        #
        context['categories_list'] = \
            self.object.getCategoriesForBrand(self.object)
        # Add in a QuerySet of all the models
        context['models_list'    ] = \
            self.object.getModelsForBrand(    self.object )
        #
        # in DetailViewGotModelAlsoPost:
        #   context['keepers_list'] = oKeeperItems
        #   context['finders_list'] = oFinderItems
        #

        return context



class BrandUpdateView( WereAnyReleventRegExColsChangedMixin,
                   GetContextForBrandCategoryList,
                   PostUpdateBrandCategoryList, UpdateViewCanCancel ):

    model           = Brand
    template_name   = 'brands/edit.html'
    form_class      = UpdateBrandForm

    success_message = 'Brand record update successfully saved!!!!'
    # success_url   = reverse_lazy('brands:detail')

    tRegExRelevantCols = (
        'cTitle',
        'cLookFor',
        'bWantPair',
        'cExcludeIf' )




class BrandIndexView( TitleSearchMixin, ListViewGotModel ):
    template_name = 'brands/index.html'
    # context_object_name = 'brand_list' # default
    model = Brand

auctionbot/templates/brands/_actions.html
<table>
<TR>
    <td>
        <form action='{% url "brands:edit" pk=brand.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" edit " />
        </form>
    </td>
    <td>
        <form action='{% url "brands:delete" pk=brand.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" delete {{ object }} brand" />
        </form>
    </td>
    <td>
        <form action='{% url "brands:add" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" add a new brand " />
        </form>
    </td>
    <td>
        <form action='{% url "brands:index" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" go to brand index " />
        </form>
    </td>
</TR>
</table>

auctionbot/templates/brands/_add_search.html
<table>
    <tr>
        <td>
            <form action="{% url "brands:add" %}">
                <input class='btn btn-primary btn-blue' type="submit" value=" add a new brand " />
            </form>
        </td>
        <td>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </td>
        <td style="text-align:right">
            <form action = "" method = "GET" >
                <input type = "text" name = "q" />
                <button class='btn btn-primary btn-blue' type = "submit" > search </button>
            </form>
        </td>
    <tr>
</table>

auctionbot/templates/brands/_brand_category_list.html
{% if all_categories_list %}

    <h3>Categories for {{ brand }}</h3>

    {{ category_help|safe }}
    <p/>
    <table>
    <tr>
        <th>include?</th><th>Category</th>
    </tr>

    {% for category in all_categories_list %}
        <tr>
            <td><input class="checkbox" name="bIncluded" type="checkbox"
                value={{ category.id }}
                {% if category.bIncluded %}checked{% endif %}></td>
            <td>{{ category.cTitle }}</td>
            <td><input name="IncludedSet" type="checkbox" style="display:none;"
                class="HIDDEN" value={{ category.id }}
                {% if category.bIncluded %}checked{% endif %}></td>
        </tr>
    {% endfor %}

    </table>
{% endif %}

auctionbot/templates/brands/actions.html
<table>
<TR>
    <td>
        <form action='{% url "brands:edit" pk=brand.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" edit " />
        </form>
    </td>
    <td>
        <form action='{% url "brands:delete" pk=brand.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" delete {{ object }} brand" />
        </form>
    </td>
    <td>
        <form action='{% url "brands:add" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" add a new brand " />
        </form>
    </td>
    <td>
        <form action='{% url "brands:index" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" go to brand index " />
        </form>
    </td>
</TR>
</table>

auctionbot/templates/brands/add.html
{% extends "base.html" %}
{% load crispy_forms_tags  %}
{% block title %}Auction Shopping Bot | Add Brand{% endblock %}


{% block content %} 

    <h1>Add a Brand</h1>
    <p>
    {% csrf_token %}

    <form action="{% url "brands:add" %}" method="post">

    <button class='btn btn-primary btn-blue' type = "submit"> Add </button>
    <input class='btn btn-primary btn-blue'  type="submit" name="cancel" value=" Cancel " />


    {% crispy form %}

    {% include "./_brand_category_list.html" %}
    <p>

    <button class='btn btn-primary btn-blue' type = "submit"> Add </button>
    <input class='btn btn-primary btn-blue'  type="submit" name="cancel" value=" Cancel " />

{% endblock %}

auctionbot/templates/brands/add_search.html
<table>
    <tr>
        <td>
            <form action="{% url "brands:add" %}">
                <input class='btn btn-primary btn-blue' type="submit" value=" add a new brand " />
            </form>
        </td>
        <td>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </td>
        <td style="text-align:right">
            <form action = "" method = "GET" >
                <input type = "text" name = "q" />
                <button class='btn btn-primary btn-blue' type = "submit" > search </button>
            </form>
        </td>
    <tr>
</table>

auctionbot/templates/brands/brand_category_list.html
{% if all_categories_list %}

    <h3>Categories for {{ brand }}</h3>

    {{ category_help|safe }}
    <p/>
    <table>
    <tr>
        <th>include?</th><th>Category</th>
    </tr>

    {% for category in all_categories_list %}
        <tr>
            <td><input class="checkbox" name="bIncluded" type="checkbox"
                value={{ category.id }}
                {% if category.bIncluded %}checked{% endif %}></td>
            <td>{{ category.cTitle }}</td>
            <td><input name="IncludedSet" type="checkbox" style="display:none;"
                class="HIDDEN" value={{ category.id }}
                {% if category.bIncluded %}checked{% endif %}></td>
        </tr>
    {% endfor %}

    </table>
{% endif %}

auctionbot/templates/brands/confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete brand "{{ object }}?"</p>
    <p>Deleting brand {{ object }} will also <b>delete all referenced models and auction items!</b></p>
    <p>This is <b>NOT</b> undoable!"</p>
    <input class='btn btn-primary btn-blue' type="submit" value="Confirm Delete" />
    <input class='btn btn-primary btn-blue' type="submit" name="cancel" value="Cancel" />
</form>

auctionbot/templates/brands/detail.html
{% extends "base.html" %}
{% load field_name %}
{% load getDashForReturn %}
{% load getLineBreakForReturn %}

{% block title %}Auction Shopping Bot | Brand {{ object.cTitle }}{% endblock %}

{% block content %}
    <h1>{{ brand }} Brand Details</h1>

    <!-- Action buttons -->
    <div class="basic">
        {% include "./_actions.html" %}
    </div>
    <!-- End Action buttons -->
    <hr>

    <table>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cTitle' %}</TD>
        <TD>{{object.cTitle}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'bWanted' %}</TD>
        <TD>{{ object.bWanted|yesno:"Yes,No" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'bAllOfInterest' %}</TD>
        <TD>{{ object.bAllOfInterest|yesno:"Yes,No" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cLookFor' %}</TD>
        <TD>{{object.cLookFor|getDashForReturn}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cKeyWords' %}</TD>
        <TD>{{object.cKeyWords|getDashForReturn}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'iStars' %}</TD>
        <TD>{{object.iStars}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cComment' %}</TD>
        <TD>{{ object.cComment | getLineBreakForReturn }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cNationality' %}</TD>
        <TD>{{ object.cNationality.name }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cExcludeIf' %}</TD>
        <TD>{{object.cExcludeIf|getDashForReturn}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'iUser' %}</TD>
        <TD>{{object.iUser}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'tCreate' %}</TD>
        <TD>{{object.tCreate|date:"d M Y  P"}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'tModify' %}</TD>
        <TD>{{object.tModify|date:"d M Y  P"}}</TD>
    </TR>
    </table>

    <p>

    <!-- Action buttons -->
    <br>

    <div class="basic">
        {% include "./_actions.html" %}
    </div>
    <br>
    <hr>
    <!-- End Action buttons -->

    <div style="margin-left:20px;margin-top:20px">
    {% if categories_list %}
        <h4>Categories for {{ brand }}</h4>
        <UL>
        {% for category in categories_list%}
            <LI><a href="{{ category.get_absolute_url }}">
                {{ category }}</a></LI>
        {% endfor %}
        </UL>
    {% endif %}
    It helps to indicate which categories apply to {{ brand }} (full explanation on edit page).
    </div>

    <hr>

    <div style="margin-left:20px;margin-top:20px">
    {% if models_list %}
        <h4>{{ brand }} Models</h4>
        <table>
        <tr>
            <td>Name/#</td>
            <td style="text-align:right"><i class="far fa-star"></i></td>
            <td>Category</td>
        </tr>
        {% for model, stars, category in models_list%}
            <tr>
                <td><a href="{{ model.get_absolute_url }}">
                    {{ model }}</a></td>
                <td style="text-align:right">{{stars}}</td>
                <td>{{category}}</td>
            </tr>
        {% endfor %}
        </table>
    {% endif %}
    </div>

    <hr>

    <form action="" method="post">
    {% csrf_token %}

      <!-- Keepers List -->
      <div class="basic">
          {% include "../keepers/_index_under_parent.html" %}
      </div>

      <hr>

      <!-- Finders List -->
      <div class="basic">
          {% include "../finders/_index_under_parent.html" %}
      </div>

    </form>

{% endblock %}

auctionbot/templates/brands/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Auction Shopping Bot Brand | {{ brand }}{% endblock %}

{% block content %} 
 
    <h1>Edit {{ brand }} Info</h1>

    <form action="{% url "brands:edit" pk=brand.id %}" method="post">

    <button class='btn btn-primary btn-blue' type = "submit"> Save </button>
    <input class='btn btn-primary btn-blue'  type="submit" name="cancel" value=" Cancel " />

    {% csrf_token %}
    {% crispy form %}

    {% include "./_brand_category_list.html" %}

    <p>
    <button class='btn btn-primary btn-blue' type = "submit"> Save </button>
    <input class='btn btn-primary btn-blue'  type="submit" name="cancel" value=" Cancel " />

    </form>

{% endblock %}

auctionbot/templates/brands/index.html
{% extends "base.html" %}
{% block title %}Auction Shopping Bot Brands{% endblock %}

{% load getDashForReturn %}

{% block content %}

    <h1>Brands</h1>

    {% include "./_add_search.html" %}

    {% if brand_list %}
        <table>
        <tr>
        <th>Brand Name</th>
        <th style="text-align:right"><i class="far fa-star"></i></th>
        <th>Wanted?</th>
        <th>Want everything?</th>
        <th>Nationality</th>
        <th>comment</th>
        </tr>
        {% for brand in brand_list %}
            <tr>
            <td><a href="{{ brand.get_absolute_url }}/">{{ brand.cTitle }}</a></td>
            <td style="text-align:right">{{ brand.iStars }}</td>
            <td>{{ brand.bWanted|yesno:"Yes,No" }}</td>
            <td>{{ brand.bAllOfInterest|yesno:"Yes,No" }}</td>
            <td style="white-space:nowrap">{{ brand.cNationality.name }}</td>
            <td>{{ brand.cComment|getDashForReturn|truncatechars:60 }}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No brands are available.</p>
    {% endif %}
    <br>
    {% include "./_add_search.html" %}

{% endblock %}