auctionbot/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

brands/urls.py
from django.conf.urls import url

from . import views



app_name = "brands"

urlpatterns = [
    url(
        regex   = r'^$',
        view    = views.BrandIndexView.as_view(),
        name    = 'index' ),
    url(
        regex   = r'^add/$',
        view    = views.BrandCreateView.as_view(),
        name    = 'add'  ),
    url(
        regex   = r'^(?P<pk>[0-9]+)/$',
        view    = views.BrandDetailView.as_view(),
        name    = 'detail'),
    url(
        regex   = r'^delete/(?P<pk>[0-9]+)/$',
        view    = views.BrandDeleteView.as_view(),
        name    = 'delete'),
    url(
        regex   = r'^edit/(?P<pk>[0-9]+)/$',
        view    = views.BrandUpdateView.as_view(),
        name    = 'edit' ),

]

'''
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new$', views.CreateBrandView.as_view(),
        name='brands-new',),
'''

searching/urls.py
from django.conf.urls import url

from . import views



app_name = "searching"

urlpatterns = [
    url(
        regex   = r'^$',
        view    = views.SearchIndexView.as_view(),
        name    = 'index' ),
    url(
        regex   = r'^add/$', # SearchViewSuccessPostFormValidMixin references
        view    = views.SearchCreateView.as_view(),
        name    = 'add'  ),
    url(
        regex   = r'^(?P<pk>[0-9]+)/$',
        view    = views.SearchDetailView.as_view(),
        name    = 'detail'),
    url(
        regex   = r'^delete/(?P<pk>[0-9]+)/$',
        view    = views.SearchDeleteView.as_view(),
        name    = 'delete'),
    url(
        regex   = r'^edit/(?P<pk>[0-9]+)/$',
        view    = views.SearchUpdateView.as_view(),
        name    = 'edit' ),
]

'''

'''

auctionbot/users/models.py
from django.db              import models
from django.urls            import reverse

from core.dj_import         import AbstractUser, _

import pytz
from timezone_field         import TimeZoneField

from ebayinfo.models        import Market

iEbayUSA = Market.objects.get(
            cMarket = 'EBAY-US' ).pk or 0 # on error may need to comment out!

# iEbayUSA = 0 # uncomment this one if the above is causing migration error

class User(AbstractUser):
    # First Name and Last Name do not cover name patterns
    # around the globe.
    name        = models.CharField(_('Name of User'), blank=True, max_length=255)
    #models.ForeignKey( Market, models.PositiveIntegerField(
    iEbaySiteID = models.ForeignKey( Market, on_delete=models.CASCADE,
                    verbose_name = 'ebay market (default)',
                    default = iEbayUSA )

    '''for testing, it is a big challenge to set default iEbaySiteID from markets table,
    because when testing, markets table starts out empty'''

    cBio        = models.TextField( 'Bio info', max_length=500, blank=True)
    cLocation   = models.CharField( 'Location', max_length=30, blank=True)
    zTimeZone   = TimeZoneField( default = 'UTC' )

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

searching/models.py
from django.db          import models

from core.utils         import getReverseWithUpdatedQuery

from ebayinfo.models    import EbayCategory

from categories.models  import Category

from core.dj_import     import get_user_model
User = get_user_model()

from searching          import ALL_PRIORITIES

from pyPks.Time.Output  import getIsoDateTimeFromDateTime


# ### models can be FAT but not too FAT! ###



class Search(models.Model):
    cTitle          = models.CharField( 'short description',
        help_text = 'This is just a short description -- ebay will not search for this<br>'
                    'you must have a) key word(s) and/or b) an ebay category',
                                         max_length = 38, null = True )
    cKeyWords       = models.TextField(
        'key words -- search for these (maximum length 350 characters)',
        max_length = 350, null = True, blank = True,
        help_text = 'What you type here will go into the ebay search box '
                    '-- mulitple terms will result in an AND search '
                    '(ebay will look for all terms).<br>'
                    'search for red OR green handbags as follows: '
                    'handbags (red,green)<br>'
                    'TIPS: to exclude words, put a - in front '
                    '(without any space),<br>'
                    'search handbags but exclude red as follows: '
                    'handbags -red<br>'
                    'search for handbags but '
                    'exclude red and green as follows: handbags -red -green' )
    # max length for a single key word is 98
    #models.ForeignKey( EbayCategory, models.PositiveIntegerField(
    iEbayCategory   = models.ForeignKey( EbayCategory,
                        on_delete=models.CASCADE,
                        verbose_name = 'ebay category',
                        null = True, blank = True,
        help_text = 'Limit search to items listed in this category' )
    # ### after updating ebay categories, check whether        ###
    # ### searches that were connected are still connected !!! ###
    iDummyCategory  = models.PositiveIntegerField( 'ebay category number',
                                null = True, blank = True,
        help_text = 'Limit search to items listed in this category<br>'
                    'copy the category number from ebay and paste here!!! (sorry)' )
    cPriority       = models.CharField( 'processing priority',
                                max_length = 2, null = True,
                                choices = ALL_PRIORITIES,
        help_text = 'high priority A1 A2 A3 ... Z9 low priority' )
    bGetBuyItNows   = models.BooleanField(
                    "also get 'Buy It Nows' (fixed price non auctions)?",
        help_text = 'You may get an avalanche of useless junk '
                    'if you turn this on -- be careful!',
                                blank = True, null = True,
                                default = False )
    bInventory    = models.BooleanField(
                    "also get 'Store Inventory' "
                    "(fixed price items in ebay stores)?",
        help_text = 'You may get an avalanche of useless junk '
                    'if you turn this on -- be careful!',
                                blank = True, null = True,
                                default = False )
    iMyCategory     = models.ForeignKey( Category,
                        on_delete=models.DO_NOTHING,
                        verbose_name = 'my category that matches ebay category',
                        null = True, blank = True,
        help_text = 'Example: if you have a category for "Manuals" and '
                    'this search is in the ebay category "Vintage Manuals" '
                    'put your "Manuals" category here.<br>If you have a '
                    'category "Widgets" and this search finds an item '
                    'with "Widget Manual" in the title, the bot will know '
                    'this item is for a manual, NOT a widget.')
    tBegSearch      = models.DateTimeField( 'last search started',
                                           null = True )
    tEndSearch      = models.DateTimeField( 'last search completed',
                                           null = True )
    cLastResult     = models.TextField( 'last search outcome', null = True )
    iUser           = models.ForeignKey( User, on_delete=models.CASCADE,
                                          verbose_name = 'Owner' )
    tCreate         = models.DateTimeField( 'created on', auto_now_add= True )
    tModify         = models.DateTimeField( 'updated on', auto_now    = True )

    def __str__(self):
        return self.cTitle

    class Meta:
        verbose_name_plural = 'searches'
        db_table        = 'searching'
        unique_together = ( ( 'iUser',      'cPriority' ),
                            ( 'iUser',      'cTitle'    ),
                            ( 'iUser',      'cKeyWords',   'iEbayCategory',) )
        ordering        = ('cTitle',)

    def get_absolute_url(self):
        #
        return getReverseWithUpdatedQuery(
                'searching:detail',
                kwargs = { 'pk': self.pk, 'tModify': self.tModify } )



class SearchLog(models.Model):
    iSearch     = models.ForeignKey( Search, on_delete=models.CASCADE,
                        verbose_name = 'Search that first found this item' )
    tBegSearch  = models.DateTimeField( 'search started',
                        db_index = True )
    tEndSearch  = models.DateTimeField( 'search completed',
                        null = True )
    tBegStore   = models.DateTimeField( 'processing started',
                        null = True )
    tEndStore   = models.DateTimeField( 'processing completed',
                        null = True )
    iItems      = models.PositiveIntegerField( 'items found',
                        null = True )
    iStoreItems = models.PositiveIntegerField( 'items stored',
                        null = True )
    iStoreUsers = models.PositiveIntegerField( 'stored for owner',
                        null = True )
    iItemHits   = models.PositiveIntegerField(
                        'have category, brand & model',
                        null = True )
    cResult     = models.TextField( 'search outcome', null = True )
    cStoreDir   = models.CharField( 'search files directory',
                                max_length = 10,
                                null = True, blank = True )
    def __str__(self):
        sSayDir = ( self.cStoreDir
                    if self.cStoreDir
                    else getIsoDateTimeFromDateTime( self.tBegSearch ) )
        return '%s - %s' % ( sSayDir, self.iSearch.cTitle )

    class Meta:
        verbose_name_plural = 'searchlogs'
        db_table            = verbose_name_plural

auctionbot/users/views.py
from django.urls                import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User

tUserFields = (
    'name',
    'iEbaySiteID',
    'cBio',
    'cLocation',
    'email',
    'zTimeZone'
    )

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'



class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = tUserFields[:-1]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User

    fields = tUserFields

    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

searching/views.py
from core.views         import ( CreateViewCanCancel, DeleteViewGotModel,
                                 DetailViewGotModel,  ListViewGotModel,
                                 UpdateViewCanCancel )

from django.urls        import reverse_lazy

from .forms             import CreateSearchForm, UpdateSearchForm

import searching.utils

from ebayinfo.models    import EbayCategory

from .mixins            import SearchViewSuccessPostFormValidMixin
from .models            import Search


# ### views assemble presentation info ###
# ###         keep views thin!         ###


class SearchCreateView(
        SearchViewSuccessPostFormValidMixin, CreateViewCanCancel ):

    model           = Search
    template_name   = 'searching/add.html'
    success_message = 'New Search record successfully saved!!!!'
    form_class      = CreateSearchForm

    success_message = 'New Search record successfully saved!!!!'


class SearchIndexView( ListViewGotModel ):

    template_name   = 'searching/index.html'
    model           = Search


class SearchDetailView( DetailViewGotModel ):

    model           = Search
    template_name   = 'searching/detail.html'
    parent          = EbayCategory


class SearchDeleteView( DeleteViewGotModel ):

    model           = Search
    template_name   = 'confirm_delete.html'
    success_message = 'Search record successfully deleted!!!!'
    success_url     = reverse_lazy('searching:index')



class SearchUpdateView( SearchViewSuccessPostFormValidMixin, UpdateViewCanCancel ):

    model           = Search
    template_name   = 'searching/edit.html'
    success_message = 'Search record update successfully saved!!!!'
    form_class      = UpdateSearchForm

    success_message = 'Search record successfully updated!!!!'

auctionbot/templates/searching/_actions.html
<table>
<TR>
    <td>
        <form action='{% url "searching:edit" pk=search.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" edit " />
        </form>
    </td>
    <td>
        <form action='{% url "searching:delete" pk=search.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" delete " />
        </form>
    </td>
    <td>
        <form action='{% url "searching:add" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" add a new search " />
        </form>
    </td>
    <td>
        <form action='{% url "searching:index" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" go to search list " />
        </form>
    </td>
</TR>
</table>

auctionbot/templates/searching/actions.html
<table>
<TR>
    <td>
        <form action='{% url "searching:edit" pk=search.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" edit " />
        </form>
    </td>
    <td>
        <form action='{% url "searching:delete" pk=search.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" delete " />
        </form>
    </td>
    <td>
        <form action='{% url "searching:add" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" add a new search " />
        </form>
    </td>
    <td>
        <form action='{% url "searching:index" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" go to search list " />
        </form>
    </td>
</TR>
</table>

auctionbot/templates/searching/add.html
{% extends "base.html" %}
{% load crispy_forms_tags  %}
{% block title %}Auction Shopping Bot | Add Search{% endblock %}

{% block content %} 

    <h1>Add a Search</h1>
    <p>
    {% csrf_token %}
    {% crispy form %}

{% endblock %}

auctionbot/templates/searching/detail.html
{% extends "base.html" %}
{% load static %}
{% load field_name %}

{% block title %}Auction Shopping Bot | Search for {{ object.cTitle }}{% endblock %}

{% block content %}
    <h1>Search for {{ object.cTitle }} - Details</h1>

    <!-- Action buttons -->
    <div class="basic">
        {% include "./_actions.html" %}
    </div>
    <!-- End Action buttons -->
    <hr>

    <table><!-- putting style="vertical-align:top" here d/n work! -->
    <TR>
        <TD width = 300>{% field_name model 'cTitle' %}</TD>
        <TD>{{object.cTitle}}</TD>
    </TR>
    <TR>
        <TD>{% field_name model 'cKeyWords' %}</TD>
        <TD style="vertical-align:top">{{ object.cKeyWords }}</TD>
    </TR>
    <TR>
        <TD>{% field_name model 'iEbayCategory' %} Name (optional)</TD>
        <TD style="vertical-align:top">{{ object.iEbayCategory|default_if_none:"" }}</TD>
    </TR>
    <TR>
        <TD>{% field_name parent 'iCategoryID' %} (optional)</TD>
        <TD style="vertical-align:top">{{ object.iEbayCategory.iCategoryID|default_if_none:"" }}</TD>
    </TR>
    <TR>
        <TD>{% field_name model 'cPriority' %}</TD>
        <TD style="vertical-align:top">{{ object.cPriority|default_if_none:"" }}</TD>
    </TR>
    <TR>
        <TD>{% field_name model 'bGetBuyItNows' %}</TD>
        <TD style="vertical-align:top">{{ object.bGetBuyItNows|yesno:"Yes,No" }}</TD>
    </TR>
    <TR>
        <TD>{% field_name model 'bInventory' %}</TD>
        <TD style="vertical-align:top">{{ object.bInventory|yesno:"Yes,No" }}</TD>
    </TR>
    <TR>
        <TD>{% field_name model 'iMyCategory' %}</TD>
        <TD style="vertical-align:top">{{ object.iMyCategory }}</TD>
    </TR>
    <TR>
        <TD>{% field_name model 'tBegSearch' %}</TD>
        <TD style="vertical-align:top">{{object.tBegSearch|date:"d M Y  P"}}</TD>
    </TR>
    <TR>
        <TD>{% field_name model 'tEndSearch' %}</TD>
        <TD style="vertical-align:top">{{object.tEndSearch|date:"d M Y  P"}}</TD>
    </TR>
    <TR>
        <TD width = 300>{% field_name model 'cLastResult' %}</TD>
        <TD style="vertical-align:top">{{object.cLastResult|default_if_none:"" }}</TD>
    </TR>
    <TR>
        <TD>{% field_name model 'iUser' %}</TD>
        <TD style="vertical-align:top">{{object.iUser}}</TD>
    </TR>
    <TR>
        <TD>{% field_name model 'tCreate' %}</TD>
        <TD style="vertical-align:top">{{object.tCreate|date:"d M Y  P"}}</TD>
    </TR>
    <TR>
        <TD>{% field_name model 'tModify' %}</TD>
        <TD style="vertical-align:top">{{object.tModify|date:"d M Y  P"}}</TD>
    </TR>
    </table>

    <hr>
    <!-- Action buttons -->
    <div class="basic">
        {% include "./_actions.html" %}
    </div>
    <!-- End Action buttons -->

</div>
{% endblock content %}

auctionbot/templates/searching/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Auction Shopping Bot Search for 
                 {{ object.cTitle }}{% endblock %}

{% block content %}

    <h1>Search for {{ object.cTitle }}</h1>

    {% csrf_token %}
    {% crispy form %}

{% endblock %}

auctionbot/templates/searching/index.html
{% extends "base.html" %}
{% block title %}Auction Shopping Bot | Searching{% endblock %}

{% block content %}

    <h1>Searches</h1>

    <form action="{% url "searching:add" %}">
        <input class='btn btn-primary btn-blue' type="submit" value=" add a new search " />
        <br>
    </form>

    {% if search_list %}
        <table>
        <tr>
        <th>Search Name</th>
        <th>ebay category</th>
        <th>priority</th>
        <th>key words</th>
        <th>last search start</th>
        <th>last search end</th>
        </tr>
        {% for search in search_list %}
            <tr>
            <td><a href="{{ search.get_absolute_url }}/">{{ search.cTitle }}</a></td>
            <td>{{ search.iEbayCategory.name }}</td>
            <td>{{ search.cPriority }}</td>
            <td>{{ search.cKeyWords|truncatechars:65 }}</td>
            <td>{{ search.tBegSearch|date:'Y-m-d H:i:s' }}</td>
            <td>{{ search.tEndSearch|date:'Y-m-d H:i:s' }}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <br>
        <p>No searches are available.</p>
    {% endif %}

    <form action="{% url "searching:add" %}">
        <input class='btn btn-primary btn-blue' type="submit" value=" add a new search " />
    </form>

{% endblock %}

auctionbot/templates/searching/items_found_detail.html
{% extends "base.html" %}
{% load field_name %}

{% block title %}Item Found {{ object.iItemNumb.cTitle }}{% endblock %}

{% block content %}

    <h1>Found {{ object }} - Details</h1>

    
    <table RULES=ROWS CELLPADDING=10>
    <TR>
        <TD width = 300>{% field_name parent  'cTitle' %}</TD> 
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD>{{object.iItemNumb.iItemNumb.cTitle}}</TD>
    </TR>
    <TR>
        <TD>{% field_name parent  'iItemNumb' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{ object.iItemNumb.iItemNumb }}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'cLocation' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.cLocation}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'cCountry' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.cCountry}}</TD>
    </TR>
    <TR>
        <TD>{% field_name parent  'cMarket' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{ object.iItemNumb.cMarket }}</TD>
    </TR>
    <TR>
        <TD width = 300>{% field_name parent  'iEbaySiteID' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.iEbaySiteID.pk}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'cGalleryURL' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP><img src="{{ object.iItemNumb.cGalleryURL }}" /></TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'cEbayItemURL' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.cEbayItemURL}}</TD>
    </TR>
    <TR>
        <TD>{% field_name parent  'tTimeBeg' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.tTimeBeg|date:"d M Y  P"}}</TD>
    </TR>
    <TR>
        <TD>{% field_name parent  'tTimeEnd' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.tTimeEnd|date:"d M Y  P"}}</TD>
    </TR>
    <TR>
        <TD>{% field_name parent  'bBestOfferable' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{ object.iItemNumb.bBestOfferable|yesno:"Yes,No" }}</TD>
    </TR>
    <TR>
        <TD>{% field_name parent  'bBuyItNowable' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{ object.iItemNumb.bBuyItNowable|yesno:"Yes,No" }}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'cListingType' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.cListingType}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'lLocalCurrency' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.lLocalCurrency}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'lCurrentPrice' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.lCurrentPrice}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'dCurrentPrice' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.dCurrentPrice}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'iCategoryID' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.iCategoryID}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'cCategory' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.cCategory}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'iCatHeirarchy' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.iCatHeirarchy.cCatHierarchy}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'i2ndCategoryID' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.i2ndCategoryID}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'c2ndCategory' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.c2ndCategory}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'i2ndCatHeirarchy' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.i2ndCatHeirarchy.cCatHierarchy}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'iConditionID' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.iConditionID}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'cCondition' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.cCondition}}</TD>
    </TR>
    <TR>
        <TD VALIGN=TOP>{% field_name parent  'cSellingState' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.cSellingState}}</TD>
    </TR>
    <TR>
        <TD>{% field_name parent  'tCreate' %}</TD>
        <TD>&nbsp;&nbsp;&nbsp;</TD>
        <TD VALIGN=TOP>{{object.iItemNumb.tCreate|date:"d M Y  P"}}</TD>
    </TR>
    </TR>
    </table>
    
    <p>
    
{% endblock %}