auctionbot/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

brands/urls.py
from django.conf.urls import url

from . import views



app_name = "brands"

urlpatterns = [
    url(
        regex   = r'^$',
        view    = views.BrandIndexView.as_view(),
        name    = 'index' ),
    url(
        regex   = r'^add/$',
        view    = views.BrandCreateView.as_view(),
        name    = 'add'  ),
    url(
        regex   = r'^(?P<pk>[0-9]+)/$',
        view    = views.BrandDetailView.as_view(),
        name    = 'detail'),
    url(
        regex   = r'^delete/(?P<pk>[0-9]+)/$',
        view    = views.BrandDeleteView.as_view(),
        name    = 'delete'),
    url(
        regex   = r'^edit/(?P<pk>[0-9]+)/$',
        view    = views.BrandUpdateView.as_view(),
        name    = 'edit' ),

]

'''
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new$', views.CreateBrandView.as_view(),
        name='brands-new',),
'''

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.core.exceptions import ImproperlyConfigured
from django.views.generic import TemplateView
from django.views import defaults as default_views



urlpatterns = [
    url(r'^$', TemplateView.as_view(
                template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(
                template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    url(r'^admin/',     include( 'admin_honeypot.urls','admin_honeypot' ), ),
    # User management
    url(r'^users/',     include(('auctionbot.users.urls', 'users')) ),
    url(r'^accounts/',  include('allauth.urls')),

    # Your stuff: custom urls includes go here

    url(r'^ebayinfo/',  include( 'ebayinfo.urls',    namespace="ebayinfo")),
    url(r'^brands/',    include( 'brands.urls',      namespace="brands")),
    url(r'^models/',    include( 'models.urls',      namespace="models")),
    url(r'^categories/',include( 'categories.urls',  namespace="categories")),
    url(r'^searching/', include( 'searching.urls',   namespace="searching")),
    url(r'^finders/',   include( 'finders.urls',     namespace="finders")),
    url(r'^keepers/',   include( 'keepers.urls',     namespace="keepers")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)





if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
                        kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
                        kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
                        kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

auctionbot/users/models.py
from django.db              import models
from django.urls            import reverse

from core.dj_import         import AbstractUser, _

import pytz
from timezone_field         import TimeZoneField

from ebayinfo.models        import Market

iEbayUSA = Market.objects.get(
            cMarket = 'EBAY-US' ).pk or 0 # on error may need to comment out!

# iEbayUSA = 0 # uncomment this one if the above is causing migration error

class User(AbstractUser):
    # First Name and Last Name do not cover name patterns
    # around the globe.
    name        = models.CharField(_('Name of User'), blank=True, max_length=255)
    #models.ForeignKey( Market, models.PositiveIntegerField(
    iEbaySiteID = models.ForeignKey( Market, on_delete=models.CASCADE,
                    verbose_name = 'ebay market (default)',
                    default = iEbayUSA )

    '''for testing, it is a big challenge to set default iEbaySiteID from markets table,
    because when testing, markets table starts out empty'''

    cBio        = models.TextField( 'Bio info', max_length=500, blank=True)
    cLocation   = models.CharField( 'Location', max_length=30, blank=True)
    zTimeZone   = TimeZoneField( default = 'UTC' )

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

auctionbot/users/views.py
from django.urls                import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User

tUserFields = (
    'name',
    'iEbaySiteID',
    'cBio',
    'cLocation',
    'email',
    'zTimeZone'
    )

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'



class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = tUserFields[:-1]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User

    fields = tUserFields

    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

auctionbot/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

auctionbot/templates/base.html
<!-- templates should be STUPID! -->
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Auction Shopping Bot{% endblock title %}</title>
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Auction Shopping Bot">
    <meta name="author" content="Rick Graves">
    <link rel="shortcut icon" type="image/png" href="{{STATIC_URL}}favicon.ico"/>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!--  -->
    <!-- This file stores project-specific CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/project.css' %}">

    <style type="text/css">
    td
    {
        padding:0 15px 0 0; /* Only right padding*/
    }
    th
    {
        padding:0 15px 0 0; /* Only right padding*/
    }
    td.num
    {
        text-align:right;
    }
    th.right
    {
        text-align:right;
    }
    td.top-margin {
      margin-top: 19px; /* need this for pagenation list links paginate.html */
    }
    </style>

    {% endblock %}

    <!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">   -->
    <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

  </head>

    <style>
    table.bottomBorder { border-collapse: collapse; }
    table.bottomBorder td,
    table.bottomBorder th {
        border-bottom: 1px solid silver;
        padding: 10px;
        text-align: left;
    }
    </style>


  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Auction Shopping Bot</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'categories:index' %}">Categories</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brands:index' %}">Brands</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'models:index' %}">Models</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'searching:index' %}">Searching</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'finders:index' %}">Finders</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'keepers:index' %}">Keepers</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container-fluid"> <!-- without -fluid the continer is fixed with big margins -->

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Choose from the menu across the top!</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
       <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
      <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> -->
      <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}
  </body>
</html>

auctionbot/templates/index_under_detail_submit.html
<table>
  <TR ALIGN=MIDDLE>
    <td>
        <input class='btn btn-primary btn-blue' type="submit" name="submit" value=" Trash Selected Items " />
    </td>
    <td>
        Carefull!  If you select keepers and hit "Trash Selected Items", you cannot undo!!!
    </td>
  </TR>
</table>

auctionbot/templates/keepers_list.html
<div style="margin-left:20px;margin-top:20px">
  {% if keepers_list %}
      <form action="" method="post">
      {% csrf_token %}
      <h4>{{ sHowMany }} {{ object.cTitle }} Keepers</h4>
      <table>
      <tr>
      <th><i class="fas fa-trash-alt"></i></th><TD>&nbsp;&nbsp;&nbsp;</TD>
      <td>Item Number</td><TD>&nbsp;&nbsp;&nbsp;</TD>
      <td>Title</td><TD>&nbsp;&nbsp;&nbsp;</TD>
      <td ALIGN=RIGHT>Price</td><TD>&nbsp;&nbsp;&nbsp;</TD>
      <td ALIGN=RIGHT>Bid Count</td><TD>&nbsp;&nbsp;&nbsp;</TD>
      <td ALIGN=RIGHT>Status</td><TD>&nbsp;&nbsp;&nbsp;</TD>
      <td ALIGN=RIGHT>End Date</td>
      </tr>
      {% for keeper in keepers_list %}
          <tr>
          <TD VALIGN=TOP><input class="checkbox" name="bTrashThis" type="checkbox" value={{ keeper.iItemNumb }}></td>
          <TD>&nbsp;&nbsp;&nbsp;</TD>
          <td VALIGN=TOP>
            <a href="https://www.ebay.com/itm/{{keeper.iItemNumb}}/">
            {{ keeper.iItemNumb }}</a></td>
          <TD>&nbsp;&nbsp;&nbsp;</TD>
          <td VALIGN=TOP><a href="{{ keeper.get_absolute_url }}">{{ keeper.cTitle }}</a></td>
          <TD>&nbsp;&nbsp;&nbsp;</TD>
          <td ALIGN=RIGHT VALIGN=TOP>{{ keeper.dConvertPrice }}</td>
          <TD>&nbsp;&nbsp;&nbsp;</TD>
          <td  ALIGN=RIGHT VALIGN=TOP>{{ keeper.iBidCount }}</td>
          <TD>&nbsp;&nbsp;&nbsp;</TD>
          <td  ALIGN=RIGHT VALIGN=TOP>{{ keeper.cListingStatus }}</td>
          <TD>&nbsp;&nbsp;&nbsp;</TD>
          <td VALIGN=TOP>
            <span style="white-space: nowrap;">{{ keeper.tTimeEnd | date:'Y-m-d' }}</span>
          </td>
          </tr>
      {% endfor %}
      </table>
      <p/>
      <table>
        <TR ALIGN=MIDDLE>
          <td>
              <input class='btn btn-primary btn-blue' type="submit" name="submit" value=" Submit " />
          </td>
          <TD>&nbsp;&nbsp;&nbsp;</TD>
          <td>
              After selecting items for the trash, you must hit Submit or all changes will be lost!
          </td>
        </TR>
      </table>
      </form>

  {% else %}
      No Keepers for {{ object.cTitle }} yet!
  {% endif %}
</div>
<p>
<p/>