auctionbot/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

brands/urls.py
from django.conf.urls import url

from . import views



app_name = "brands"

urlpatterns = [
    url(
        regex   = r'^$',
        view    = views.BrandIndexView.as_view(),
        name    = 'index' ),
    url(
        regex   = r'^add/$',
        view    = views.BrandCreateView.as_view(),
        name    = 'add'  ),
    url(
        regex   = r'^(?P<pk>[0-9]+)/$',
        view    = views.BrandDetailView.as_view(),
        name    = 'detail'),
    url(
        regex   = r'^delete/(?P<pk>[0-9]+)/$',
        view    = views.BrandDeleteView.as_view(),
        name    = 'delete'),
    url(
        regex   = r'^edit/(?P<pk>[0-9]+)/$',
        view    = views.BrandUpdateView.as_view(),
        name    = 'edit' ),

]

'''
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new$', views.CreateBrandView.as_view(),
        name='brands-new',),
'''

models/urls.py
from django.conf.urls import url

from . import views


app_name = "models"

urlpatterns = [
    url(
        regex   = r'^$',
        view    = views.ModelIndexView.as_view(),
        name    = 'index' ),
    url(
        regex   = r'^(?P<pk>[0-9]+)/$',
        view    = views.ModelDetailView.as_view(),
        name    = 'detail'),
    url(
        regex   = r'^edit/(?P<pk>[0-9]+)/$',
        view    = views.ModelUpdateView.as_view(),
        name    = 'edit' ),
    url(
        regex   = r'^delete/(?P<pk>[0-9]+)/$',
        view    = views.ModelDeleteView.as_view(),
        name    = 'delete'),
    url(
        regex   = r'^add/$',
        view    = views.ModelCreateView.as_view(),
        name    = 'add'  ),

]
'''

'''

archive/models.py
from django.db                  import models
from django_countries.fields    import CountryField

# Create your models here.

from django.contrib.auth        import get_user_model

User = get_user_model()



class Item(models.Model):
    iItemNumb       = models.BigIntegerField( 'ebay item number',
                        primary_key = True )
    cDescription    = models.TextField( 'description',
                        null = True, blank = True ) # d/n always get
    bBestOfferable  = models.BooleanField( 'buy it now enabled?',
                        default = False )
    tTimeBeg        = models.DateTimeField( 'beginning date/time',null=True )
    tTimeEnd        = models.DateTimeField( 'ending date/time',   null=True )
    cEbayItemURL    = models.CharField( 'ebay item URL', max_length =188 )
    cListingType    = models.CharField( 'listing type', max_length = 15 )
    cLocation       = models.CharField( 'location', max_length = 48 )
    cPaymentMethods = models.CharField( 'ebay item URL', max_length = 88 )
    cGalleryURL     = models.CharField( 'gallery pic URL',
                        max_length = 88, null = True, blank = True )
    cPictureURLs    = models.TextField( 'picture URLs',
                        null = True, blank = True )
    cPostalCode     = models.CharField( 'postal code', max_length = 12,
                        null = True, blank = True )
    iCategoryID     = models.PositiveIntegerField( 'primary category ID',
                        null = True, blank = True )
    cCategory       = models.CharField( 'primary category',
                        max_length = 48 )
    iQuantity       = models.SmallIntegerField( 'quantity' )
    cSellerID       = models.CharField( 'seller user name', max_length = 48 )
    iFeedbackScore  = models.BigIntegerField( 'seller feedback score' )
    cFeedbackPercent= models.CharField( 'seller feedback percent', max_length = 8 )
    iBidCount       = models.SmallIntegerField( 'bid count' )
    dConvertPrice   = models.DecimalField( # form was throwing nonsense error
                        'price (converted)',        # for MoneyField
                        max_digits=10, decimal_places=2,    # but not for
                        db_index = False )                  # DecimalField
    cConvertCurrency= models.CharField( 'local currency converted to this',
                        max_length = 3, default = 'USD' )
    lLocalPrice     = models.DecimalField( 'price (local currency)',
                        max_digits = 10, decimal_places = 2,
                        null = True, blank = True )
    lLocalCurrency  = models.CharField( 'local currency',
                        max_length = 3, default = 'USD' )
    cHighBidder     = models.CharField( 'high bidder user name',
                        max_length = 48, null = True, blank = True )
    cListingStatus  = models.CharField( 'Listing Status', max_length = 18 )
    iQuantitySold   = models.SmallIntegerField( 'quantity sold' )
    cShipToLocations= models.TextField( 'ship to locations' )
    cSite           = models.CharField( 'Site', max_length = 14 )
    cTimeLeft       = models.CharField( 'time left', max_length =18 )
    cTitle          = models.CharField( 'item title',
                        max_length = 80 )
    iHitCount       = models.SmallIntegerField( 'Hit Count',
                        null = True, blank = True ) # ebay d/n always include
    cCategoryIDs    = models.CharField( 'category IDs',   max_length =  88 )
    cCategoryNames  = models.CharField( 'category names', max_length = 148 )
    cCountry        = CountryField( "Country" )
    cReturnPolicy   = models.CharField( 'Return Policy', max_length = 48 )
    dMinimumBid     = models.DecimalField( 'Minimum Bid',
                        max_digits = 12, decimal_places = 2,
                        null = True, blank = True )
    cBidCurrency    = models.CharField( 'bid currency',
                        max_length = 3, default = 'USD',
                        null = True, blank = True )
    iConditionID    = models.SmallIntegerField( 'Condition ID',
                        null = True, blank = True )
    cCondition      = models.CharField( 'condition display name',
                        max_length = 28, null = True, blank = True )
    bGlobalShipping = models.BooleanField( 'Global Shipping', default=False )

    bBuyItNowable   = models.BooleanField(
                        'buy it now enabled?',default = False )
    lBuyItNowPrice  = models.DecimalField( 'buy it now price (local currency)',
                        max_digits = 10, decimal_places = 2,
                        null = True, blank = True )
    lBuyItNowCurrenc= models.CharField( 'buy it now local currency',
                        max_length = 3, default = 'USD',
                        null = True, blank = True )
    dBuyItNowPrice  = models.DecimalField(
                        'buy it now price (converted)',
                        max_digits=10, decimal_places=2,
                        null = True, blank = True )
    cBuyItNowConvert= models.CharField(
                        'buy it now local currency converted to this',
                        max_length = 3, default = 'USD',
                        null = True, blank = True )

    tCreate         = models.DateTimeField( 'created on',
                        db_index = True, auto_now_add= True )

    tModify         = models.DateTimeField( 'updated on', null = True )

    bGotPictures    = models.BooleanField( 'pictures downloaded?',
                        default = False )
    tGotPictures    = models.DateTimeField( 'pictures downloaded',
                        null = True )
    iGotPictures    = models.PositiveSmallIntegerField(
                        'how many pictures downloaded',
                        null = True, blank = True )

    def __str__(self):
        return str( self.iItemNumb )

    class Meta:
        verbose_name_plural = 'items'
        db_table            = verbose_name_plural



class ItemImage(models.Model):
    iItemNumb       = models.BigIntegerField(
                        'ebay item number', primary_key = True )
    isequence       = models.PositiveSmallIntegerField( 'sequence' )
    cfilename       = models.CharField( 'local file name', max_length = 28 )
    coriginalurl    = models.TextField( 'original URL' )
    iUser           = models.ForeignKey( User, verbose_name = 'Owner' )
    tCreate         = models.DateTimeField( 'created on', auto_now_add= True )

    def __str__(self):
        return self.iItemNumb

    class Meta:
        verbose_name_plural = 'itemimages'
        db_table            = verbose_name_plural
        unique_together     = ('iItemNumb', 'isequence',)
#

auctionbot/users/models.py
from django.db              import models
from django.urls            import reverse

from core.dj_import         import AbstractUser, _

import pytz
from timezone_field         import TimeZoneField

from ebayinfo.models        import Market

iEbayUSA = Market.objects.get(
            cMarket = 'EBAY-US' ).pk or 0 # on error may need to comment out!

# iEbayUSA = 0 # uncomment this one if the above is causing migration error

class User(AbstractUser):
    # First Name and Last Name do not cover name patterns
    # around the globe.
    name        = models.CharField(_('Name of User'), blank=True, max_length=255)
    #models.ForeignKey( Market, models.PositiveIntegerField(
    iEbaySiteID = models.ForeignKey( Market, on_delete=models.CASCADE,
                    verbose_name = 'ebay market (default)',
                    default = iEbayUSA )

    '''for testing, it is a big challenge to set default iEbaySiteID from markets table,
    because when testing, markets table starts out empty'''

    cBio        = models.TextField( 'Bio info', max_length=500, blank=True)
    cLocation   = models.CharField( 'Location', max_length=30, blank=True)
    zTimeZone   = TimeZoneField( default = 'UTC' )

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

core/models.py
from django.db  import models

from .validators import gotTextOutsideParens

# ### models can be FAT but not too FAT! ###


class ModelCanYieldFieldNamesAndValuesMixin( object ):
    '''
    This lets you do:

    for field, val in object:
        print field, val
    '''
    def __iter__(self):
        #
        bYieldRest = False
        #
        for field in self._meta.get_fields():
            #
            value = getattr( self, field.name, None )
            #
            yield ( field.name, value )



sLookForHeading = ( 'Considered a hit if this text is found '
    '(optional -- if you include, bot will also search for this)' )

sTitleHelpText = (
    'Put the %s name here -- '
    'Bot will search for this in the auction title %sfor each item found.<br/>'
    'Optionally, you can put additional description in parentheses ().  '
    'While searching auction titles, bot will ignore anything in parentheses.' )

sLookForHelpText = (
    'Put nick names, common misspellings and alternate %s names here -- '
    'leave blank if Bot only needs to look for the %s name.<br>'
    '%s'
    'Each line is evaluated separately, '
    'Bot will know item is in this %s if any one line matches.' )

sKeyWordsHelpText = (
    'Putting text here is optional, '
    'but if there is text here, robot will consider it REQUIRED '
    '-- must be found in the title %s'
    '<b>IN ADDITION TO</b> %s name.<br>'
    'Put alternate key words on separate lines -- '
    'Bot will know item is for this %s if words '
    'on any one line match.' )

sExcludeIfHelpText = (
    'Bot will know item is <b>NOT</b> of this %s if '
    'any one line matches (each line evaluated separately, '
    'put different exclude tests on different lines)')

class IntegerRangeField(models.PositiveSmallIntegerField):
    def __init__(self,
            verbose_name=None, name=None, min_value=None, max_value=None,
            **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.PositiveSmallIntegerField.__init__(
            self, verbose_name, name, **kwargs)
    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value':self.max_value}
        defaults.update(kwargs)
        return super().formfield(**defaults)


# from https://stackoverflow.com/questions/19498740/how-can-i-make-all-charfield-in-uppercase-direct-in-model

class UpperCaseCharField(models.CharField):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    def pre_save(self, model_instance, add):
        value = getattr(model_instance, self.attname, None)
        if value:
            value = value.upper()
            setattr(model_instance, self.attname, value)
            return value
        else:
            return super().pre_save( model_instance, add )

# Create your models here.

class gotSomethingOutsideTitleParensCharField( models.CharField ):
    #
    validators = [ gotTextOutsideParens, ]

itemhits/models.py
from django.db              import models
from django_countries.fields \
                            import CountryField

# Create your models here.

from models.models          import Model
from brands.models          import Brand
from categories.models      import Category

from django.contrib.auth import get_user_model
User = get_user_model()



class ItemImage(models.Model):
    iItemNumb       = models.BigIntegerField(
                        'ebay item number', primary_key = True )
    isequence       = models.PositiveSmallIntegerField( 'sequence' )
    cfilename       = models.CharField( 'local file name', max_length = 28 )
    coriginalurl    = models.TextField( 'original URL' )
    iUser           = models.ForeignKey( User, verbose_name = 'Owner' )
    tCreate         = models.DateTimeField( 'created on', auto_now_add= True )
    
    def __str__(self):
        return self.iItemNumb

    class Meta:
        verbose_name_plural = 'itemimages'
        db_table            = verbose_name_plural
        unique_together     = ('iItemNumb', 'isequence',)
#

models/admin.py
from django.contrib     import admin

from core.admin         import admin_method_attributes

from .models            import Model

from pyPks.Utils.Output import getSayYesOrNo
from pyPks.String.Get   import getUpToLenSplitOnWhite

class ModelAdmin(admin.ModelAdmin):
    list_display = (
        "cTitle",
        "_cKeyWords", "_iStars", "_iBrand", "_iCategory",
        "_cComment" )
    readonly_fields = (
        "_cKeyWords", "_iStars", "_iBrand", "_iCategory",
        "_cComment", 'iLegacyKey' )

    @admin_method_attributes( short_description='Key words', allow_tags=True )
    def _cKeyWords(self, obj):
        return str( obj.cKeyWords ).replace( ' ', '&nbsp;' )

    #@admin_method_attributes( short_description='Required?' )
    #def _bKeyWordRequired(self, obj):
        #return getSayYesOrNo( obj.bKeyWordRequired )

    @admin_method_attributes( short_description='Desireability' )
    def _iStars(self, obj):
        return obj.iStars

    @admin_method_attributes( short_description='Brand', allow_tags=True )
    def _iBrand(self, obj):
        return str( obj.iBrand ).replace( ' ', '&nbsp;' )

    @admin_method_attributes( short_description='Category', allow_tags=True )
    def _iCategory(self, obj):
        return str( obj.iCategory ).replace( ' ', '&nbsp;' )

    def _cComment(self, obj):

        sComment = str( obj.cComment )

        if len( sComment ) > 80:
            sComment = getUpToLenSplitOnWhite( sComment, 76 ) + ' ...'

        return sComment


admin.site.register(Model, ModelAdmin)

models/apps.py
from django.apps import AppConfig


class ModelsConfig(AppConfig):
    name = 'models'

auctionbot/users/views.py
from django.urls                import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User

tUserFields = (
    'name',
    'iEbaySiteID',
    'cBio',
    'cLocation',
    'email',
    'zTimeZone'
    )

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'



class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = tUserFields[:-1]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User

    fields = tUserFields

    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

auctionbot/templates/models/_actions.html
<table>
<TR>
    <td>
        <form action='{% url "models:edit" pk=object.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" edit " />
        </form>
    </td>
    <td>
        <form action='{% url "models:delete" pk=object.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" delete {{ object }} model " />
        </form>
    </td>
    <td>
        <form action='{% url "models:add" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" add a new model " />
        </form>
    </td>
    <td>
        <form action='{% url "models:index" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" go to model index " />
        </form>
    </td>
</TR>
</table>

auctionbot/templates/models/_add_search.html
<table>
    <tr>
        <td>
            <form action="{% url "models:add" %}">
                <input class='btn btn-primary btn-blue' type="submit" value=" add a new model " />
            </form>
        </td>
        <td>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </td>
        <td style="text-align:right">
            <form action = "" method = "GET" >
                <input type = "text" name = "q" />
                <button class='btn btn-primary btn-blue' type = "submit" > search </button>
            </form>
        </td>
    <tr>
</table>

auctionbot/templates/models/actions.html
<table>
<TR>
    <td>
        <form action='{% url "models:edit" pk=object.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" edit " />
        </form>
    </td>
    <td>
        <form action='{% url "models:delete" pk=object.id %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" delete {{ object }} model " />
        </form>
    </td>
    <td>
        <form action='{% url "models:add" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" add a new model " />
        </form>
    </td>
    <td>
        <form action='{% url "models:index" %}'>
            <input class='btn btn-primary btn-blue' type="submit" value=" go to model index " />
        </form>
    </td>
</TR>
</table>

auctionbot/templates/models/add.html
{% extends "base.html" %}
{% load crispy_forms_tags  %}
{% block title %}Auction Shopping Bot | Add Model{% endblock %}

{% block content %} 

    <h1>Add a Model</h1>
    <p>
    {% csrf_token %}
    {% crispy form %}

{% endblock %}

auctionbot/templates/models/add_search.html
<table>
    <tr>
        <td>
            <form action="{% url "models:add" %}">
                <input class='btn btn-primary btn-blue' type="submit" value=" add a new model " />
            </form>
        </td>
        <td>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </td>
        <td style="text-align:right">
            <form action = "" method = "GET" >
                <input type = "text" name = "q" />
                <button class='btn btn-primary btn-blue' type = "submit" > search </button>
            </form>
        </td>
    <tr>
</table>

auctionbot/templates/models/confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete model "{{ object }}?"</p>
    <p>Deleting model {{ object }} will also <b>delete all referenced auction items!</b></p>
    <p>This is <b>NOT</b> undoable!"</p>
    <input class='btn btn-primary btn-blue' type="submit" value="Confirm Delete" />
    <input class='btn btn-primary btn-blue' type="submit" name="cancel" value="Cancel" />
</form>

auctionbot/templates/models/detail.html
{% extends "base.html" %}
{% load static %}
{% load field_name %}
{% load getDashForReturn %}

{% block title %}Auction Shopping Bot | {{ object.iBrand|default_if_none:"" }}
                 Model {{ object }}{% endblock %}

{% block content %}
    <h1>Model {{ object }} Details</h1>

    <!-- Action buttons -->
    <div class="basic">
        {% include "./_actions.html" %}
    </div>
    <!-- End Action buttons -->
    <hr>

    <table>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cTitle' %}</TD>
        <TD>{{object.cTitle}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'iBrand' %}</TD>
        <TD style="white-space:nowrap"><a href="{{ object.iBrand.get_absolute_url }}/">{{ object.iBrand|default_if_none:"" }}</a></TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'iCategory' %}</TD>
        <TD style="white-space:nowrap"><a href="{{ object.iCategory.get_absolute_url }}/">{{ object.iCategory }}</a></TD>
    </TR>
    <TR style="vertical-align:top">
        <TD style="white-space:nowrap">{% field_name model 'cKeyWords' %}</TD>
        <TD>{{object.cKeyWords|getDashForReturn}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cLookFor' %}</TD>
        <TD>{{object.cLookFor|getDashForReturn}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'iStars' %}</TD>
        <TD>{{object.iStars}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD style="white-space:nowrap">{% field_name model 'bSubModelsOK' %}</TD>
        <TD>{{ object.bSubModelsOK|yesno:"Yes,No" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'bMustHaveBrand' %}</TD>
        <TD>{{ object.bMustHaveBrand|yesno:"Yes,No" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'bWanted' %}</TD>
        <TD>{{ object.bWanted|yesno:"Yes,No" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'bGenericModel' %}</TD>
        <TD>{{ object.bGenericModel|yesno:"Yes,No" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'bGetPictures' %}</TD>
        <TD>{{ object.bGetPictures|yesno:"Yes,No" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'bGetDescription' %}</TD>
        <TD>{{ object.bGetDescription|yesno:"Yes,No" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cComment' %}</TD>
        <TD>{{ object.cComment | getLineBreakForReturn }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cExcludeIf' %}</TD>
        <TD>{{object.cExcludeIf|getDashForReturn }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cFileSpec1' %}</TD>
        <TD>{{object.cFileSpec1|default_if_none:"" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cFileSpec2' %}</TD>
        <TD>{{object.cFileSpec2|default_if_none:"" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cFileSpec3' %}</TD>
        <TD>{{object.cFileSpec3|default_if_none:"" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cFileSpec4' %}</TD>
        <TD>{{object.cFileSpec4|default_if_none:"" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'cFileSpec5' %}</TD>
        <TD>{{object.cFileSpec5|default_if_none:"" }}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'iUser' %}</TD>
        <TD>{{object.iUser}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'tCreate' %}</TD>
        <TD>{{object.tCreate|date:"d M Y  P"}}</TD>
    </TR>
    <TR style="vertical-align:top">
        <TD>{% field_name model 'tModify' %}</TD>
        <TD>{{object.tModify|date:"d M Y  P"}}</TD>
    </TR>
    </table>
    <!-- Action buttons -->
    <br>
    <div class="basic">
        {% include "./_actions.html" %}
    </div>
    <br>
    <hr>
    <!-- End Action buttons -->

    <form action="" method="post">
    {% csrf_token %}

      <!-- Keepers List -->
      <div class="basic">
          {% include "../keepers/_index_under_parent.html" %}
      </div>

      <hr>
      <!-- Finders List -->
      <div class="basic">
          {% include "../finders/_index_under_parent.html" %}
      </div>

    </form>

    <br>
    <hr>

</div>
{% endblock content %}

auctionbot/templates/models/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Auction Shopping Bot | update {{ object.iBrand|default_if_none:"" }} 
                 Model {{ object.cTitle }}{% endblock %}

{% block content %}

    <h1>{{ object.iBrand |default_if_none:""}} Model {{ object.cTitle }}</h1>

    {% csrf_token %}
    {% crispy form %}

{% endblock %}

auctionbot/templates/models/index.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Auction Shopping Bot Models{% endblock %}
{% load getDashForReturn %}


{% block content %}
  <h2>Models</h2>

    {% include "./_add_search.html" %}

    {% if object_list %}
        {# the pagination section #}
        {% if is_paginated %}
            {% include "../common/_paginate.html" %}
        {% endif %}
        <div class="container">
        <div class="list-group">
        <table class="bottomBorder">
        <tr>
        <th>Model Name/Number</th>
        <th>Brand</th>
        <th>Category</th>
        <th style="text-align:right"><i class="far fa-star"></i></th>
        <th>Comment</th>
        </tr>
        {% for model in object_list %}
            <tr>
            <td style="white-space:nowrap"><a href="{{ model.get_absolute_url }}">{{ model.cTitle }}</a></td>
            <td style="white-space:nowrap"><a href="{{ model.iBrand.get_absolute_url }}/">{{ model.iBrand }}</a></td>
            <td style="white-space:nowrap"><a href="{{ model.iCategory.get_absolute_url }}/">{{ model.iCategory }}</td>
            <td style="text-align:right">{{ model.iStars}}</td>
            <td>{{ model.cComment|getDashForReturn|truncatechars:45}}</td>
            </tr>
        {% endfor %}
        </table>
        </div>
        </div>
        {# the pagination section #}
        {% if is_paginated %}
          {% include "../common/_paginate.html" %}
        {% endif %}
    {% else %} <!-- brand_list -->
        <p>No models are available.</p>
    {% endif %} <!-- brand_list -->

    {% include "./_add_search.html" %}

{% endblock content %}